image: bradrydzewski/php:5.5
script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-interaction --no-progress
    - php vendor/bin/phpunit -c phpunit.xml.dist    
